### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by lmuzquiz** [michalsnik/aos#375]
## This is:

- Bug

## Specifications

  - AOS version: 2.3.3
  - OS: OS X, Node 8.1.3, npm 5.5.1
  - Browser: Any browser.

## Expected Behavior
to work normally 

## Actual Behavior
ERROR in ./node_modules/aos/dist/aos.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/aos/.babelrc" at 0, attempted to resolve relative to "/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/aos"
    at /Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/lmuzquiz/Documents/GitHub/EGS/node_modules/babel-loader/lib/index.js:173:20)
 @ ./dev/js/modules/index.js 14:0-22
 @ ./dev/js/main.js
 @ multi webpack-hot-middleware/client?reload=true ./main.js

## Possible Solution

 .babelrc (from aos) should be added to .npmignore and so never published on npm.

**Comment by michalsnik** [comment]
`aos@next` doesn't have `.babelrc`
