### ISSUE TITLE
Error during build with Gridsome

### ISSUE THREAD

**Issue by SteveVercellin** [michalsnik/aos#533]
## This is:

[x] Bug
- Feature request
[x] Question
- Idea

## Specifications

  - AOS version: aos@3.0.0-beta.6
  - OS: MacOS Catalina 10.15.2 (19C57)
  - Browser: Chrome / Safari / Mozilla

**Packages:**

```JSON

{
  "name": "newhrslab",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "aos": "^3.0.0-beta.6",
    "gridsome": "^0.7.0",
    "vuetify": "^2.2.1"
  },
  "devDependencies": {
    "style-resources-loader": "^1.3.3",
    "webpack-node-externals": "^1.7.2"
  }
}

```

## Expected Behavior
`gridsome Build` should be successful

## Actual Behavior
Running the command  `gridsome Build` cause this error:

```
$ gridsome build
Gridsome v0.7.12


Initializing plugins...

Load sources - 0s

Create GraphQL schema - 0.02s
Create pages and templates - 0.11s
Generate temporary code - 0.02s
Bootstrap finish - 5.57s
Compiling assets...

Compile assets - 33.28s

Execute GraphQL (8 queries) - 0s
Write out page data (8 files) - 0s

Could not generate HTML for "/design/":

/Users/imac/Documents/GitHub/newhrslab/node_modules/aos/dist/aos.css:1
[data-aos][data-aos][data-aos-duration="50"],body[data-aos-duration="50"] [data-aos]{transition-duration:50ms}[data-aos][data-aos][data-aos-delay="50"],body[data-aos-delay="50"] [data-aos]{transition-delay:0s}[data-aos][data-aos][data-aos-delay="50"].aos-animate,body[data-aos-delay="50"] [data-aos].aos-animate{transition-delay:50ms}[data-aos][data-aos][data-aos-duration="100"],body[data-aos-duration="100"] [data-aos]{transition-duration:.1s}[data-aos][data-aos][data-aos-delay="100"],body[data-aos-delay="100"] [data-aos]{transition-delay:0s}[data-aos][data-aos][data-aos-delay="100"].aos-animate,body[data-aos-delay="100"] [data-aos].aos-animate{transition-delay:.1s}[data-aos][data-aos][data-aos-duration="150"],body[data-aos-duration="150"] [data-aos]{transition-duration:.15s}[data-aos][data-aos][data-aos-delay="150"],body[data-aos-delay="150"] [data-aos]{transition-delay:0s}[data-aos][data-aos][data-aos-delay="150"].aos-animate,body[data-a

SyntaxError: Invalid left-hand side in assignment
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/imac/Documents/GitHub/newhrslab/node_modules/vue-server-renderer/build.prod.js:1:77673
    at Object.<anonymous> (webpack:/external "aos/dist/aos.css":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)

Total task duration: 44.96s


```

## Steps to Reproduce the Problem

1. Set-up an environment with Vue, Gridsome, and Vuetify.
2.  Install AOS
3.  Run `gridsome develop` and then `gridsome build`.

## Detailed Description

during dev environment, everything works fine, when launching the build will throw the error.
I tried with the previous version of AOS: same error.

**Comment by austinbakker** [comment]
Having the same issues, have not found a solution

**Comment by chinedu16** [comment]
I am having the same issues, i hvae tried downgrading aos versions and still nothing

![Screenshot 2020-05-22 at 2 45 22 PM](https://user-images.githubusercontent.com/18489240/82674258-ead3b280-9c3a-11ea-9257-10efd4681ab4.png)

**Comment by BilendM** [comment]
Anyone found a solution to this?

**Comment by raulbethencourt** [comment]
Hey I found a solution 🎉 to the problem. It's not very clean but I arrive to build.
I put this in my main.js
```
head.link.push({
     rel: 'stylesheet',
     href: 'https://unpkg.com/aos@next/dist/aos.css'
});
```
to get the css in cdn

I've installed plugin with:
npm install aos --save

and i Put this to my page script:
```
<script>
//aos plugin
import AOS from '../../node_modules/aos/dist/aos';

export default {
    data: () => ({
        show: false,
        isActive: false,
        btn: false
    }),
    mounted() {
        AOS.init({ disable: 'phone', duration: 1200 });
    }
};
</script>
```

I hope it works for you
