### ISSUE TITLE
Console Error but the animations still work

### ISSUE THREAD

**Issue by kaweepatinn1** [michalsnik/aos#831]
## This is:
- Bug

## Specifications

  - AOS version: 2.3.1
  - OS: Windows 10
  - Browser: Chrome

## Expected Behavior
No console error on page load

## Actual Behavior
Console error: 
aos.js:1 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at Object.A [as init] (aos.js:1:1620)
    at aos.js:1:5
but the aos animations still work

## Steps to Reproduce the Problem

```
$(document).ready(function(){
  AOS.init({
    disable: 'phone tablet mobile', //not sure if this is the proper syntax, but removing it still causes the error, so I've kept it in
  });
  });
```
 as the javascript, being called at

```
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="static/js/aos.js"></script>
```

 in html

live:
https://nanomotions.org/index.html

**Comment by kaweepatinn1** [comment]
I dont know how but it seems to have fixed itself? I committed and pushed and the issue disappeared so I guess this issue is solved
